aaa:
  enabled: true

system:
  ffmpeg-path: /usr/local/bin/ffmpeg
  recxxx-path: /usr/local/bin/recdvb
  epgdump-path: /usr/local/bin/epgdump
  webcam-device-name: /dev/video0
  webcam-audio-name: hw:0,0
  webcam-audio-channel: 2
  temporary-path: /tmp/chukasa
  file-path: /opt/chukasa/video
  ffmpeg-threads: 1

common:
  tuner: tuner.json
  channel-configuration: channel_configuration.json
  video-file-extension: ts,m2t,mp4,mov,mpg,mpeg,vob,avi,divx,wmv,flv,ogg,ogm,iso

epg:
 epgdump-temporary-path: /tmp/chukasa_epgdump
 epgdump-recording-duration: 32
 epgdump-execute-schedule-cron: 0 0 7 * * *
 epgdump-execute-on-boot-ignore-interval: 86400000

hls:
  duration: 2
  uri-in-playlist: 3

recorder:
  start-margin: 30
  stop-margin: 0

hyaruka:
  scheme: http
  host: localhost
  port: 49149
  api-version: v1
  enabled: true
  unix-domain-socket-enabled: false

server:
  port: 8080

logging:
  path: logs
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

spring:
  profiles:
    active: localhost-no-database
  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
      # m3u8, ts の Content-Type に ; charset=UTF-8 が付くのを防ぐ
  http:
    encoding:
      force: false
---
spring:
  profiles: localhost-no-database
server:
  port: 8080
---
spring:
  profiles: localhost-mongodb
  # MongoDB
  # if want to use this application on Docker, change -> ex. "spring.data.mongodb.host=mongo"
  # spring.data.mongodb.host=mongo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chukasa
      server-selection-timeout: 500
---
spring:
  profiles: localhost-hsqldb
---
spring:
  profiles: localhost-postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/chukasa
    username: chukasa
    password: chukasa
---
spring:
  profiles: localhost-mongodb-postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/chukasa
    username: chukasa
    password: chukasa
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chukasa
      server-selection-timeout: 500
---
spring:
  profiles: localhost-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/chukasa # TODO: not working...
    username: chukasa
    password: chukasa
---
spring:
  profiles: localhost-mongodb-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/chukasa # TODO: not working...
    username: chukasa
    password: chukasa
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chukasa
      server-selection-timeout: 500
---
spring:
  profiles: gae-flexible-postgresql
  datasource:
    url: jdbc:postgresql://google/chukasa?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=
    username: chukasa
    password: chukasa
  jpa:
     hibernate:
       ddl-auto: create
---
spring:
  profiles: localhost-docker-mongodb-postgresql
  datasource:
    url: jdbc:postgresql://postgres:5432/chukasa
    username: chukasa
    password: chukasa
  data:
    mongodb:
      host: mongo
      port: 27017
      database: chukasa
      server-selection-timeout: 500